In [1]:
import jax.numpy as jnp


In [2]:
r = 5
sten_i = jnp.arange(-r, r + 1, dtype=jnp.int32)


In [3]:
sten_i

Array([-5, -4, -3, -2, -1,  0,  1,  2,  3,  4,  5], dtype=int32)

In [14]:
g_int = jnp.array([4,3,5,1,-3])
sten_r = jnp.arange(-r, r + 1, dtype=jnp.float32)             # (2r+1,)

sx, sy = jnp.meshgrid(sten_r, sten_r, indexing='ij')     # (2r+1)**2 each 


In [23]:
sten_i

Array([-5, -4, -3, -2, -1,  0,  1,  2,  3,  4,  5], dtype=int32)

In [27]:
(g_int[:, None] + sten_i[None, :])

Array([[-1,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [-2, -1,  0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [-4, -3, -2, -1,  0,  1,  2,  3,  4,  5,  6],
       [-8, -7, -6, -5, -4, -3, -2, -1,  0,  1,  2]], dtype=int32)